### ISSUE TITLE
Make interferopy a real package

### ISSUE THREAD

**Issue by rameyer** [mladenovak/interferopy#2]
Should we make interferopy an "installable package" (not a pip package yet)? It currently bugs me that I need the folder present next to any script that uses it. Also, would make editing and testing of the example.py in the current structure possible!
Happy to do it - it's very simple.

**Comment by GiantMolecularCloud** [comment]
You can install any github repo with pip:
`python -m pip install git+https://github.com/mladenovak/interferopy`

To install a specific commit, add the commit with an "@"
`python -m pip install git+https://github.com/mladenovak/interferopy@4357d513b3aaf4f91dfe6385f2ec938e798206ee`

**Comment by rameyer** [comment]
I didn't know this! Uploading to pip is only one click away, but this is even better. 

However when trying what you suggest, I get a nasty error - what seems to be missing here is the "setup.py" using the setuptools library necessary to have this work as a package. Not a big deal, but I'll wait until my pull request is accepted before starting a new one.

    ERROR: Command errored out with exit status 1:
     command: /Users/rameyer/anaconda3/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/z4/gdnsv6jn6jxclk95wst5tn8h0000gn/T/pip-req-build-bb0gpxgi/setup.py'"'"'; __file__='"'"'/private/var/folders/z4/gdnsv6jn6jxclk95wst5tn8h0000gn/T/pip-req-build-bb0gpxgi/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/z4/gdnsv6jn6jxclk95wst5tn8h0000gn/T/pip-pip-egg-info-bdiqdq12
         cwd: /private/var/folders/z4/gdnsv6jn6jxclk95wst5tn8h0000gn/T/pip-req-build-bb0gpxgi/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/rameyer/anaconda3/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/z4/gdnsv6jn6jxclk95wst5tn8h0000gn/T/pip-req-build-bb0gpxgi/setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by mladenovak** [comment]
Agreed. It should be made into a normal installable package. Please do look into it.

Currently, I am just appending a path to any script that would use it:

    import sys
    sys.path.append("path-to-folder-containing-interferopy")
