### ISSUE TITLE
pypa release

### ISSUE THREAD

**Issue by lboogaard** [mladenovak/interferopy#29]
Some things may still be required before we can release on pypa. Checkout the documentation and the openastronomy checklist:
- https://packaging.python.org/
- https://packaging-guide.openastronomy.org/en/latest/minimal.html

**Comment by rameyer** [comment]
Indeed, namely the metadata and version specifiers must be done properly. Probably need to change 'requirements.txt' in setup.cfg and change setup.py accordingly.

**Comment by lboogaard** [comment]
Great, I merged the install changes.
