### ISSUE TITLE
readthedocs sync with github releases

### ISSUE THREAD

**Issue by rameyer** [mladenovak/interferopy#31]
It would be nice to set up readthe docs such that the docs are update for every release (see quick tuto here: https://docs.readthedocs.io/en/stable/webhooks.html). 

Therefore, we need @lboogaard to get the webhook from admin dashboard of the docs and send it to @mladenovak who is the only one able to setup webhooks in this repo (see link above on how to). 

By the way @mladenovak, do we have your blessing to go public?

**Comment by mladenovak** [comment]
I like the docs! The webhook is in place, and you have my blessings.
