### ISSUE TITLE
Using the correct celestial reference system

### ISSUE THREAD

**Issue by mladenovak** [mladenovak/interferopy#33]
I've noticed the FK5 system is explicitly mentioned a few times [(example)](https://github.com/mladenovak/interferopy/blame/32d6e29312f6ea18a5e846ea44c58ba3946408dc/interferopy/tools.py#L572). This is fine most of the time, but for some ultra high resolution observations, it might make a small but nasty systematic offset. It would be best to output whichever system is used in the fits file. As far as I know, ALMA defaults to ICRS, not FK5.

**Comment by lboogaard** [comment]
[From ALMA Cycle 3 on, the reference frame is ICRS by default](https://help.almascience.org/kb/articles/how-do-i-combine-cycle-1-and-or-2-measurementsets-and-images-with-ones-from-other-cycles-j2000). Unfortunately, this is not found in the header often (e.g., our testdata does not have the `RADESYS` keyword). We should update the examples to ICRS to be consistent. 

However, I think it will be up to the user to use the correct system for their particular radio images.

**Comment by rameyer** [comment]
I'll have to check for NOEMA - maybe a solution would be to scan for an ALMA or NOEMA header, and only then default to ICRS. That way radio/other images are not affected.
