### ISSUE TITLE
Organisation

### ISSUE THREAD

**Issue by rameyer** [mladenovak/interferopy#34]
@lboogaard  @mladenovak  Isn't a github "interferopy" organisation the best long-term solution to collaboration, code ownership and privileges on the repo with people coming and going into the project?

https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/about-organizations

**Comment by rameyer** [comment]
@lboogaard @mladenovak 

OK: ASCL does not accept submissions without a paper specifically on the code. Zenodo does. Zenodo requires linking your Github account to the Zenodo account, so only repos you own or the organization your are into owns can be uploaded/managed/released. 

I propose 1) creating the 'interferopy' organization 2) transferring (by fork, e.g. the original repos will stay here) mladenonvak/interferopy to interferopy/interferopy. I can do everything today but just need @mladenovak to do the transfer/fork. I will add you all in the interferopy org of course.

**Comment by rameyer** [comment]
OK, another update: transferring means losing ownership of the repo, and I'm sure @mladenovak  wants to keep this repo in his profile for his portfolio. Therefore, the only way is to fork this repo, and transfer the forked repo to the organisation. I'll do this shortly. We will need to link again all the readthedocs, and open again all the issues.

**Comment by mladenovak** [comment]
It's fine. I think the original link actually keeps working after transferring ownership and should redirect to the new place. I'll make the transfer in the evening.

**Comment by rameyer** [comment]
Ok, if you're sure, let's go for this then. This will avoid the hassle of linking again readthedocs and all the issues.. Thanks!

**Comment by mladenovak** [comment]
The power is yours
