### ISSUE TITLE
Tabs or Spaces

### ISSUE THREAD

**Issue by lboogaard** [mladenovak/interferopy#7]
The code is currently TAB identented, which I personally dislike, and so does [PEP8](https://www.python.org/dev/peps/pep-0008/#tabs-or-spaces). Any objections to changing this to spaces?

**Comment by mladenovak** [comment]
Well, if the standard is progressing toward spaces, then it can be exchanged with spaces. Once Romain and you take over this in earnest, you can decide how to proceed. I have been using tabs for years now, so allow me to use them for a few more weeks :D

Curious, why do you dislike tabs? I always found it practical to have just one character per indent, and IDEs allow you to setup the appearance of a tab to a desired number of spaces.

**Comment by lboogaard** [comment]
Perhaps it comes down to the IDE. In mine, spaces are more convenient.

I now realise there is a big downside to this change, which is that it will effectively break the git history (as changes will be hard to track through it). Which is also an argument to change this sooner rather than later (if we decide to do so).

**Comment by rameyer** [comment]
I would go by PEP8 standard... Also PyCharm has an option to reformat everything to PEP8 automatically so I could do that and push at some point where there is no other PR.

**Comment by lboogaard** [comment]
Yes, now that you brought it up, `flake8` is giving a lot of syntax warnings. If you want to fix these in one go, that would be great!
