### ISSUE TITLE
Develop install

### ISSUE THREAD

**Issue by lboogaard** [mladenovak/interferopy#9]
I like using `python setup.py develop` (or equivalent `pip install -e .`), so I can continue working on the source code without having to reinstall the package every time I do an edit (see [setuptools](https://setuptools.readthedocs.io/en/latest/userguide/development_mode.html)). For some reason, his didn't work for me with `interferopy`, however...

I have traced this back to a long-standing issue with develop installs (see [https://github.com/pypa/pip/issues/3160](https://github.com/pypa/pip/issues/3160) and [https://github.com/pypa/setuptools/issues/230](https://github.com/pypa/setuptools/issues/230)). It boils down to the fact that the code sits in `interferopy/src/` and not in a folder that has the same name as the package. As far as I can see, there are a few common workarounds:

- move the source to `interferopy/interferopy/` (easiest solution?)
- move the source to `interferopy/src/interferopy/` and change `package_dir = { '' : 'src' }` in `setup.py`

Another hack is to symlink `interferopy/interferopy -> src`, but that isn't a solution.

I'll look at the setuptools docs to see if there is a better solution. But in any case, any thoughts/preferences on this matter? I'm happy to do a PR with the preferred option.

**Comment by mladenovak** [comment]
I have to personal attachment to the name "src", so a simple rename sounds good to me, unless this renaming can introduce new problems.
